### ISSUE TITLE
Certain images fail to load consistently

### ISSUE THREAD

**Issue by nickgdyer** [brenoprata10/ng2-image-viewer#29] opened 2019-07-20 14:45 UTC
We're using ng2-image-viewer in a Cordova Project and loading Images as Base64 from the device storage and using push to place the Base64 strings into an array. This works fine for nearly all images but for some obscure reason we have certain images that will not display and instead the "spinner" remains on the screen with no error reported in the Console or anything. If this was random then I would suspect coding issues but this happens only with certain images and only those images. I have attached two example BASE64 strings in the zip
[Temp.zip](https://github.com/brenoprata10/ng2-image-viewer/files/3413717/Temp.zip)
. An example of one that works and one of the ones that does not. I am a bit unsure how to go about finding out what is wrong.

**Comment by nickgdyer** [comment] 2019-07-21 15:26
Wondering whether this is a similar issue to #28  and is something to do with file size. If I pass the string with the data: image/*...etc header then I also get the net::ERR_INVALID_URL error. If I strip the prefix/header out of the image strings then I get no error at all.

**Comment by nickgdyer** [comment] 2019-07-21 16:34
So now I am almost certainly convinced this is a file size issue. I have tested the code on literally dozens of images in the App we have embedded ng2-image-viewer into and the image only refuses to appear when image BASE64 string appears to be over approx 1MB in size. I have attached a file with a smple of my tests however my actual testing is over a far greater number of images than shown in the attachment. It would as I say above, appear to be something to do with a max size of the Base64 string.

In the sample data attached are two separate multimedia tours consisting of parts of the tour. For each Tour there are three images, one is an opener image, one is a map, and a closer image.  I have shown for each image in each part of each tour the size of the image Base64 string as well as the first 100 chars of the Base64 string. I have also indicated whether the image loaded OK or not. It becomes apparent that a break point around 1MB seems to indeed exist unless anybody else has some ideas.

For now to get round this we're going to reduce the DPI and overall size of the images pending some form of feedback.

I hope somebody finds this information of help.

[sampledata.txt](https://github.com/brenoprata10/ng2-image-viewer/files/3414798/sampledata.txt)

**Comment by Amine-28** [comment] 2019-08-08 10:08
Hello Sir, 
I was trying all day to load Images as Base64 from the device storage and using push to place the Base64 strings as you did but I couldn' find the solution... I couldn't find exactly how to use the push method, can you please help me with the code that has the push in it?

**Comment by brenoprata10** [comment] 2019-08-09 17:54
@nickgdyer Sorry for the wait and thanks for your good feedback, i'll look at it this weekend :)

**Comment by brenoprata10** [comment] 2019-08-09 17:56
@Amine-28 if you're having problems with pushing, i recommend you taking a look at #24 there's a working example attached on it :)

**Comment by Amine-28** [comment] 2019-08-15 10:42
Hello Breno,
Thank you so much for the help it worked perfectly, then I faced an error when updating images and thanks to you I solved it with your help on issue #21 : 

`this.images = [...this.images, newImage(Ex: https://picsum.photos/400/700/?random)];`

again thank you so much I really appreciate it.

**Comment by KuzSerg** [comment] 2019-08-21 06:29
Good day.
I also have a similar problem with base64 files whose size is larger than 1.2 MB. Please tell me when this problem will be resolved? And has anyone solved this problem already?

**Comment by KuzSerg** [comment] 2019-08-21 06:29
> So now I am almost certainly convinced this is a file size issue. I have tested the code on literally dozens of images in the App we have embedded ng2-image-viewer into and the image only refuses to appear when image BASE64 string appears to be over approx 1MB in size. I have attached a file with a smple of my tests however my actual testing is over a far greater number of images than shown in the attachment. It would as I say above, appear to be something to do with a max size of the Base64 string.
> 
> In the sample data attached are two separate multimedia tours consisting of parts of the tour. For each Tour there are three images, one is an opener image, one is a map, and a closer image. I have shown for each image in each part of each tour the size of the image Base64 string as well as the first 100 chars of the Base64 string. I have also indicated whether the image loaded OK or not. It becomes apparent that a break point around 1MB seems to indeed exist unless anybody else has some ideas.
> 
> For now to get round this we're going to reduce the DPI and overall size of the images pending some form of feedback.
> 
> I hope somebody finds this information of help.
> 
> [sampledata.txt](https://github.com/brenoprata10/ng2-image-viewer/files/3414798/sampledata.txt)

Good day.
Is a solution to your problem found or not yet?

**Comment by nickgdyer** [comment] 2019-08-21 09:28
Not too my knowledge, not as yet. I got round it by simply resampling the images as High-Res was not essential to the over look and feel for where this package was being used. Once I got them all under 1MB everything seemed to work just fine.

**Comment by damithmalalanayake** [comment] 2019-09-27 17:49
I'm also having an issue with the size of images. Hope this will fix soon.
Thanks

**Comment by ckafkamac** [comment] 2019-09-27 20:29
I'm 90% sure this is due to the regex to determine how the string is interpreted not being pinned to the beginning of the string. This means that any base64 image string that contains the magic letter combinations "www", "http" or "https" would trigger the wrong behaviour and break the image viewer.

See pull request #35

**Comment by damithmalalanayake** [comment] 2019-09-29 19:05
@brenoprata10 Please release a version, if the issue is fixed by the commit of @ckafkamac 
Thanks

**Comment by brenoprata10** [comment] 2019-10-02 21:27
Just released `3.0.5`
Check it on: https://www.npmjs.com/package/ng2-image-viewer/v/3.0.5

**Comment by BeritJanssen** [comment] 2019-10-03 16:01
Thanks a ton! Unfortunately, this didn't fix the loading issue I had. I wonder whether it's to do with the loading of the image, i.e., if the timeout of the loading (set to 1 second) doesn't suffice to fetch the images array? After clicking "next" or "previous", the image viewer works perfectly.

I'm not using base64 images but fetch the images from the backend.

**Comment by brenoprata10** [comment] 2019-10-03 16:20
@BeritJanssen I tested images using 3g mode on chrome web tools and that took 6 seconds to load from picsum, is there any errors on the network tab?

**Comment by BeritJanssen** [comment] 2019-10-03 18:57
Thank you, Breno. Indeed, you are right, it's not the loading time. The error occurs mostly after the first load of the page. It seems that my issue is different from the one raised here.

**Comment by brenoprata10** [comment] 2019-10-03 18:59
Try using `loadOnInit` true

**Comment by damithmalalanayake** [comment] 2019-10-04 17:56
> Just released `3.0.5`
> Check it on: https://www.npmjs.com/package/ng2-image-viewer/v/3.0.5

Thanks!

**Comment by brenoprata10** [comment] 2019-12-09 10:41
Closing issue due to inactivity

**Closed as completed by brenoprata10** 2019-12-09 10:41 UTC
Labels: bug
